[theme]
primaryColor = "#2563eb"
backgroundColor = "#faf8ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#131b2e"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
